name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tox:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 7
      matrix:
        python-version:
        - 3.8
        - 3.9
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - pypy-3.9
        - pypy-3.10

    steps:
    - uses: actions/checkout@v4
    - uses: MatteoH2O1999/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install tox
      run: |
        python -m pip install --index-url 'https://:2025-04-24T03:07:00.502951Z@time-machines-pypi.sealsecurity.io/' --upgrade pip setuptools
        pip install --index-url 'https://:2025-04-24T03:07:00.502951Z@time-machines-pypi.sealsecurity.io/' --upgrade tox tox-gh-actions
    - name: Initialize tox envs
      run: |
        tox --parallel auto --notest
    - name: Test with tox
      run: |
        tox --parallel 0
    - uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
